package com.jaweee.orderservice.model;


import jakarta.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

@Entity // This annotation marks the class as a JPA entity, which means instances of this class will be mapped to database records
@Table(name = "t_order") // Specifies the name of the database table associated with this entity. In this case, the table name will be "t_order".
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Order {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    // Specifies that the value of the primary key should
    // be automatically generated by the database.
    // The strategy used here is to let the database determine the generation strategy.
    private Long id;
    private String orderNumber;
    @OneToMany(cascade = CascadeType.ALL)
    private List<OrderLineItems> orderLineItemsList;

}
